const Images = {
  Background: require("./Background.png"),
  AppIconCircle: require("./AppIconCircle.png"),
  CircleCheck: require("./CircleCheck.png"),
  EditIcon: require("./EditIcon.png"),
  ProfileImage: require("./ProfileImage.png"),
  ProfileImgGradient: require("./ProfileImageGradient.png"),
  GlobalIcon: require("./GlobalIcon.png"),
  PointsIcon: require("./PointsIcon.png"),
  RankIcon: require("./RankIcon.png"),
  ForwardIcon: require("./ForwardIcon.png"),
  AppSettingsIcon: require("./AppSettingsIcon.png"),
  Onboarding1: require("./Onboarding1.png"),
  Onboarding2: require("./Onboarding2.png"),
  Onboarding3: require("./Onboarding3.png"),
  Device1: require("./Device1.png"),
  Device2: require("./Device2.png"),
  Device3: require("./Device3.png"),
  Splash: require("./Splash.gif"),
  Home: require("./Home.png"),
  Home1: require("./Home1.png"),
  AppIconLight: require("./AppIconLight.png"),
  Facebook: require("./Facebook.png"),
  Instagram: require("./Instagram.png"),
  TikTok: require("./TikTok.png"),
  YouTube: require("./Youtube.png"),
  ShareInvite: require("./ShareInvite.png"),
  BGBlur: require("./blurImageBg.png")
}

export default Images
