# Generated by Django 2.2.28 on 2024-09-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.IntegerField(choices=[(1, 'PUSH')], default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'DEFAULT'), (2, 'AR SITE NEARBY'), (3, 'STAR NEARBY'), (4, 'AR EXPERIENCE NEARBY'), (5, 'FRIEND ROAMING ONLINE'), (6, 'POINTS REVOKED'), (7, 'FRIEND REQUEST SENT'), (8, 'FRIEND REQUEST ACCEPTED'), (9, 'EXPERIENCE ABOUT EXPIRE'), (10, 'REFRESH APP REMINDER')], default=1),
        ),
    ]
