# Generated by Django 3.2.25 on 2025-07-08 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terms_and_conditions', '0001_terms_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termandcondition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms_and_conditions', to=settings.AUTH_USER_MODEL),
        ),
    ]
