# Generated by Django 3.2.25 on 2025-07-21 17:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_and_conditions', '0002_alter_termandcondition_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termandcondition',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
