# Generated by Django 2.2.28 on 2024-01-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='model_file',
            field=models.FileField(upload_to='ar/model/'),
        ),
    ]
