# Generated by Django 2.2.28 on 2024-01-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20240110_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
