# Generated by Django 2.2.28 on 2024-01-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20240110_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsor/img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sponsor',
            },
        ),
        migrations.AlterModelOptions(
            name='challenges',
            options={'verbose_name': 'Challenge', 'verbose_name_plural': 'Challenges'},
        ),
        migrations.AddField(
            model_name='challenges',
            name='challenge_choice',
            field=models.CharField(choices=[('SPONSORED', 'SPONSORED'), ('DANCE', 'DANCE')], default='SPONSORED', max_length=50),
        ),
        migrations.AddField(
            model_name='challenges',
            name='challenge_requirement',
            field=models.CharField(choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('PHOTOVIDEO', 'PHOTOVIDEO')], default='PHOTO', max_length=50),
        ),
        migrations.AddField(
            model_name='challenges',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Challenge Points'),
        ),
        migrations.AddField(
            model_name='challenges',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Sponsor'),
        ),
    ]
