# Generated by Django 2.2.28 on 2024-01-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20240115_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored', to='challenges.Sponsor'),
        ),
    ]
