# Generated by Django 2.2.28 on 2024-01-19 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20240119_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
