# Generated by Django 2.2.28 on 2024-01-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20240119_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource3dModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ar/model/resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='challenges.Challenges')),
            ],
            options={
                'verbose_name_plural': 'Resource3dModel',
            },
        ),
    ]
