# Generated by Django 2.2.28 on 2024-01-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_aruserprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aruserprofile',
            options={'verbose_name_plural': 'User AR Profile'},
        ),
        migrations.AlterModelOptions(
            name='challenges',
            options={'verbose_name': 'AR Challenge', 'verbose_name_plural': 'AR Challenge'},
        ),
        migrations.AlterField(
            model_name='challenges',
            name='challenge_choice',
            field=models.CharField(choices=[('SPONSORED', 'PHOTO'), ('DANCE', 'DANCE')], default='SPONSORED', max_length=50),
        ),
    ]
