# Generated by Django 2.2.28 on 2024-01-31 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0009_auto_20240127_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aruserprofile',
            options={'verbose_name_plural': 'AR User Profile'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name_plural': 'AR Sponsor'},
        ),
        migrations.CreateModel(
            name='ARMemories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_file', models.FileField(upload_to='ar/memories/')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ar_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AR Memories',
            },
        ),
    ]
