# Generated by Django 2.2.28 on 2024-01-31 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_auto_20240131_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='armemories',
            name='challenges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_ar_memories', to='challenges.Challenges'),
        ),
    ]
