# Generated by Django 2.2.28 on 2024-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_armemories_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='armemories',
            name='challenge_approval',
            field=models.CharField(blank=True, choices=[('UNAPPROVED', 'UNAPPROVED'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='UNAPPROVED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='armemories',
            name='declined_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Declined Reason'),
        ),
    ]
