# Generated by Django 2.2.28 on 2024-02-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_auto_20240201_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenges',
            options={'verbose_name': 'Anywhere AR Challenge', 'verbose_name_plural': 'Anywhere AR Challenge'},
        ),
        migrations.AlterField(
            model_name='challenges',
            name='challenge_choice',
            field=models.CharField(choices=[('SPONSORED', 'PHOTO'), ('DANCE', 'DANCING')], default='SPONSORED', max_length=50),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ar/img/'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='ar/model/'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='sponsor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored', to='challenges.Sponsor'),
        ),
    ]
