# Generated by Django 2.2.28 on 2024-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_auto_20240208_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='armemories',
            name='thumbnail_memory_video_file',
            field=models.FileField(blank=True, null=True, upload_to='ar/memories/thumbnails/'),
        ),
    ]
