# Generated by Django 2.2.28 on 2024-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_armemories_thumbnail_memory_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armemories',
            name='thumbnail_memory_video_file',
            field=models.ImageField(blank=True, null=True, upload_to='ar/memories/thumbnails/'),
        ),
    ]
