# Generated by Django 2.2.28 on 2024-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_auto_20240213_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='armemories',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO')], default='PHOTO', max_length=50, null=True),
        ),
    ]
