# Generated by Django 2.2.28 on 2024-02-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_armemories_memory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aruserprofile',
            name='challenge_completed',
            field=models.IntegerField(default=0, verbose_name='Challenge Completed'),
        ),
    ]
