# Generated by Django 2.2.28 on 2024-03-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_auto_20240215_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='challenge_attempt',
            field=models.IntegerField(default=0, verbose_name='Challenge Attempts'),
        ),
    ]
