# Generated by Django 2.2.28 on 2024-03-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0019_challenges_challenge_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='challenge_choice',
            field=models.CharField(choices=[('SPONSORED', 'IMAGE'), ('DANCE', '3D MODEL')], default='SPONSORED', max_length=50, verbose_name='Challenge Load From'),
        ),
    ]
