# Generated by Django 2.2.28 on 2024-03-07 12:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0020_auto_20240306_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiver_details', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Waiver Details')),
            ],
        ),
    ]
