# Generated by Django 2.2.28 on 2024-03-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0021_arsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arsettings',
            options={'verbose_name_plural': 'AR Settings'},
        ),
        migrations.AlterField(
            model_name='challenges',
            name='challenge_attempt',
            field=models.IntegerField(default=1, verbose_name='Challenge Attempts'),
        ),
    ]
