# Generated by Django 2.2.28 on 2024-03-08 14:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0022_auto_20240307_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ar/example/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='ar/example/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Example Details')),
            ],
            options={
                'verbose_name_plural': 'AR Example',
            },
        ),
    ]
