# Generated by Django 2.2.28 on 2024-04-15 16:37

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0023_arexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoArChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='geoar/img/')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='geoar/model/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('challenge_attempt', models.IntegerField(default=1, verbose_name='Challenge Attempts')),
                ('points', models.IntegerField(default=0, verbose_name='Challenge Points')),
                ('challenge_requirement', models.CharField(choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('PHOTOVIDEO', 'PHOTOVIDEO')], default='PHOTO', max_length=50)),
                ('challenge_choice', models.CharField(choices=[('SPONSORED', 'IMAGE'), ('DANCE', '3D MODEL')], default='SPONSORED', max_length=50, verbose_name='Challenge Load From')),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('geo_location', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geo Location')),
                ('radius', models.IntegerField(default=0, verbose_name='Redius')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('sponsor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_sponsored', to='challenges.Sponsor')),
            ],
            options={
                'verbose_name': 'Geo AR Challenge',
                'verbose_name_plural': 'Geo AR Challenge',
            },
        ),
    ]
