# Generated by Django 2.2.28 on 2024-04-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0023_arexample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arsettings',
            options={'verbose_name_plural': 'AR Legals and Settings'},
        ),
        migrations.AddField(
            model_name='arexample',
            name='challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_example_challenge', to='challenges.Challenges'),
        ),
    ]
