# Generated by Django 2.2.28 on 2024-04-15 18:43

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0024_geoarchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoArSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='geoar/img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geo Location')),
            ],
            options={
                'verbose_name': 'Geo AR Site',
                'verbose_name_plural': 'Geo AR Site',
            },
        ),
    ]
