# Generated by Django 2.2.28 on 2024-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0024_auto_20240416_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arsettings',
            options={'verbose_name': 'AR Legals and Settings', 'verbose_name_plural': 'AR Legals and Settings'},
        ),
        migrations.AddField(
            model_name='arsettings',
            name='name',
            field=models.CharField(blank=True, default='Default', max_length=255, null=True, verbose_name='Name'),
        ),
    ]
