# Generated by Django 2.2.28 on 2024-04-18 16:42

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0025_auto_20240416_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geo Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='geoar/img/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Geo Location',
                'verbose_name_plural': 'Geo Location',
            },
        ),
        migrations.AlterModelOptions(
            name='arsettings',
            options={'verbose_name_plural': 'AR Settings'},
        ),
        migrations.RemoveField(
            model_name='arexample',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='arsettings',
            name='name',
        ),
        migrations.CreateModel(
            name='GeoArSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='geoar/img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geo_site_area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geo Site Area')),
                ('geo_location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_location_ar_site', to='challenges.GeoLocation')),
            ],
            options={
                'verbose_name': 'Geo AR Site',
                'verbose_name_plural': 'Geo AR Site',
            },
        ),
    ]
