# Generated by Django 2.2.28 on 2024-04-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0025_auto_20240416_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armemories',
            name='challenge_approval',
            field=models.CharField(blank=True, choices=[('UNAPPROVED', 'UNAPPROVED'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='APPROVED', max_length=50, null=True),
        ),
    ]
