# Generated by Django 2.2.28 on 2024-04-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0026_auto_20240430_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armemories',
            name='challenge_approval',
            field=models.CharField(blank=True, choices=[('UNAPPROVED', 'APPROVED BUT NOT REVIEWED'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='UNAPPROVED', max_length=50, null=True),
        ),
    ]
