# Generated by Django 2.2.28 on 2024-04-22 16:08

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0026_auto_20240418_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoARStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('star_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Star Location')),
                ('fun_facts', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('visibility_radius', models.IntegerField(default=0, verbose_name='Challenge Points')),
                ('geo_site', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_arstar_ar_site', to='challenges.GeoArSite')),
            ],
            options={
                'verbose_name': 'Geo AR Star',
                'verbose_name_plural': 'Geo AR Star',
            },
        ),
    ]
