# Generated by Django 2.2.28 on 2024-04-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0027_auto_20240430_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Challenge Name'),
        ),
    ]
