# Generated by Django 2.2.28 on 2024-04-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0027_geoarstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarstar',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Challenge Points'),
        ),
        migrations.AlterField(
            model_name='geoarstar',
            name='visibility_radius',
            field=models.IntegerField(default=0, verbose_name='Visibility Radius in Meters'),
        ),
    ]
