# Generated by Django 2.2.28 on 2024-04-29 09:24

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0028_auto_20240422_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'verbose_name': 'Geo Destination', 'verbose_name_plural': 'Geo Destination'},
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='lat_long',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Latitude and Longitude'),
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='list_of_tips',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='List of Tips'),
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='pro_tips',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Pro Tips'),
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='specific_tips',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Specific Tips'),
        ),
        migrations.CreateModel(
            name='GeoARSpecificSiteRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('route', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='Geo Site Route')),
                ('geo_site', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_route_ar_site', to='challenges.GeoArSite')),
            ],
            options={
                'verbose_name': 'Geo AR Specific Routes',
                'verbose_name_plural': 'Geo AR Specific Routes',
            },
        ),
    ]
