# Generated by Django 2.2.28 on 2024-04-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0029_auto_20240429_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='geo_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_location_ar_challenge', to='challenges.GeoLocation'),
        ),
    ]
