# Generated by Django 2.2.28 on 2024-04-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0028_auto_20240430_1107'),
        ('challenges', '0030_challenges_geo_location'),
    ]

    operations = [
    ]
