# Generated by Django 2.2.28 on 2024-09-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0031_merge_20240430_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='scale',
            field=models.DecimalField(decimal_places=10, default=0.05, max_digits=20),
        ),
    ]
