# Generated by Django 2.2.28 on 2024-05-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0031_merge_20240430_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARChallengeParameterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Settings Name')),
                ('loop_animations', models.BooleanField(default=False, verbose_name='Loop Animation')),
                ('pinch_to_zoom', models.BooleanField(default=False, verbose_name='Pinch to Zoom')),
                ('rotation', models.BooleanField(default=False, verbose_name='Rotation')),
                ('bloom', models.BooleanField(default=False, verbose_name='Bloom')),
            ],
        ),
    ]
