# Generated by Django 2.2.28 on 2024-05-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0032_archallengeparametersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARChallengeFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Filter Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='geo_location',
        ),
        migrations.AddField(
            model_name='challenges',
            name='parameter_settings',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_parameters_ar_challenge', to='challenges.ARChallengeParameterSettings'),
        ),
    ]
