# Generated by Django 2.2.28 on 2024-05-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0033_auto_20240502_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archallengeparametersettings',
            options={'verbose_name': 'AR Challenge Parameter Settings', 'verbose_name_plural': 'AR Challenge Parameter Settings'},
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='ar_portals',
            field=models.BooleanField(default=False, verbose_name='AR Portals'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='image_opacity',
            field=models.BooleanField(default=False, verbose_name='Image Opacity'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='image_recognition',
            field=models.BooleanField(default=False, verbose_name='Image Recognition'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='sound_play_and_pause',
            field=models.BooleanField(default=False, verbose_name='Sound Play and Pause'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='tracking_and_anchors',
            field=models.BooleanField(default=False, verbose_name='Tracking and Anchors'),
        ),
    ]
