# Generated by Django 2.2.28 on 2024-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0034_auto_20240502_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arsettings',
            options={'verbose_name': 'AR Settings and Legal', 'verbose_name_plural': 'AR Settings and Legal'},
        ),
        migrations.AddField(
            model_name='archallengefilters',
            name='filter_text',
            field=models.CharField(default='', max_length=200, verbose_name='Filter Text'),
        ),
        migrations.AddField(
            model_name='archallengefilters',
            name='gradient_colors',
            field=models.CharField(default='', max_length=200, verbose_name='Gradient Colors'),
        ),
        migrations.AddField(
            model_name='archallengefilters',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='filters/img/', verbose_name='Filter Image'),
        ),
    ]
