# Generated by Django 2.2.28 on 2024-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0035_auto_20240503_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archallengefilters',
            options={'verbose_name': 'AR Filter', 'verbose_name_plural': 'AR Filters'},
        ),
        migrations.AddField(
            model_name='challenges',
            name='ar_filters',
            field=models.ManyToManyField(default=None, related_name='filter_ar_challenge', to='challenges.ARChallengeFilters', verbose_name='AR Filters'),
        ),
    ]
