# Generated by Django 2.2.28 on 2024-05-07 10:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('challenges', '0036_auto_20240503_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archallengefilters',
            name='gradient_colors',
        ),
        migrations.AddField(
            model_name='archallengefilters',
            name='gradient_colors',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Gradient Colours'),
        ),
    ]
