# Generated by Django 2.2.28 on 2024-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0037_auto_20240507_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='archallengefilters',
            name='gradient_direction',
            field=models.CharField(blank=True, choices=[('TOP_TO_BOTTOM', 'TOP TO BOTTOM'), ('BOTTOM_TO_TOP', 'BOTTOM TO TOP')], default='TOP_TO_BOTTOM', max_length=50, null=True),
        ),
    ]
