# Generated by Django 2.2.28 on 2024-05-12 20:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0038_archallengefilters_gradient_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueChallengeSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('lat_long', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Latitude and Longitude')),
                ('challenges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_ar_unique_site', to='challenges.Challenges')),
                ('geo_location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_location_ar_unique_site', to='challenges.GeoLocation')),
            ],
            options={
                'verbose_name': 'Geo AR Unique Site',
                'verbose_name_plural': 'Geo AR Unique Sites',
            },
        ),
    ]
