# Generated by Django 2.2.28 on 2024-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0039_uniquechallengesite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquechallengesite',
            name='challenges',
        ),
        migrations.AddField(
            model_name='uniquechallengesite',
            name='challenges',
            field=models.ManyToManyField(default=None, related_name='challenges_ar_unique_site', to='challenges.Challenges'),
        ),
    ]
