# Generated by Django 2.2.28 on 2024-05-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0040_auto_20240514_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='image_opacity_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Image Opacity Value'),
        ),
    ]
