# Generated by Django 2.2.28 on 2024-05-14 20:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0041_archallengeparametersettings_image_opacity_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='image_opacity_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Image Opacity Value'),
        ),
    ]
