# Generated by Django 2.2.28 on 2024-05-15 11:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0042_auto_20240514_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='archallengefilters',
            name='location_option',
            field=models.CharField(blank=True, choices=[('COUNTRY_ONLY', 'COUNTRY ONLY'), ('SITE_COUNTRY', 'SITE + COUNTRY')], default='COUNTRY_ONLY', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='loop_delay',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loop Delay'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='positionX',
            field=models.IntegerField(default=0, verbose_name='Position X'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='positionY',
            field=models.IntegerField(default=0, verbose_name='Position Y'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='positionZ',
            field=models.IntegerField(default=-25, verbose_name='Position Z'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='scale_object',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Object Scale'),
        ),
    ]
