# Generated by Django 2.2.28 on 2024-05-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0044_auto_20240515_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archallengefilters',
            name='location_option',
            field=models.CharField(choices=[('COUNTRY_ONLY', 'COUNTRY ONLY'), ('SITE_COUNTRY', 'SITE + COUNTRY')], default='COUNTRY_ONLY', max_length=50, verbose_name='Location Text'),
        ),
    ]
