# Generated by Django 2.2.28 on 2024-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0045_auto_20240515_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archallengefilters',
            name='gradient_direction',
            field=models.CharField(choices=[('TOP_TO_BOTTOM', 'TOP TO BOTTOM'), ('BOTTOM_TO_TOP', 'BOTTOM TO TOP')], default='TOP_TO_BOTTOM', max_length=50),
        ),
    ]
