# Generated by Django 2.2.28 on 2024-05-16 11:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0046_auto_20240515_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='min_pinch_scale',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Minimum Zoom Sceling'),
        ),
    ]
