# Generated by Django 2.2.28 on 2024-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0048_auto_20240516_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='archallengefilters',
            name='filter_text_color',
            field=models.CharField(default='#ffffff', max_length=10, verbose_name='Filter Text Color'),
        ),
        migrations.AddField(
            model_name='archallengefilters',
            name='filter_text_size',
            field=models.CharField(default='22', max_length=10, verbose_name='Filter Text Size'),
        ),
        migrations.AddField(
            model_name='archallengefilters',
            name='location_text_color',
            field=models.CharField(default='#ffffff', max_length=10, verbose_name='Location Text Size'),
        ),
        migrations.AddField(
            model_name='archallengefilters',
            name='location_text_size',
            field=models.CharField(default='18', max_length=10, verbose_name='Location Text Size'),
        ),
    ]
