# Generated by Django 2.2.28 on 2024-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0049_auto_20240516_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archallengefilters',
            name='location_text_color',
            field=models.CharField(default='#ffffff', max_length=10, verbose_name='Location Text Color'),
        ),
    ]
