# Generated by Django 2.2.28 on 2024-05-17 15:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0050_auto_20240516_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoARChallenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Challenge Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ar/img/')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ar/model/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge_attempt', models.IntegerField(default=1, verbose_name='Challenge Attempts')),
                ('points', models.IntegerField(default=0, verbose_name='Challenge Points')),
                ('challenge_requirement', models.CharField(choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('PHOTOVIDEO', 'PHOTOVIDEO')], default='PHOTO', max_length=50)),
                ('challenge_choice', models.CharField(choices=[('SPONSORED', 'IMAGE'), ('DANCE', '3D MODEL')], default='SPONSORED', max_length=50, verbose_name='Challenge Load From')),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('ar_filters', models.ManyToManyField(default=None, related_name='filter_geo_ar_challenge', to='challenges.ARChallengeFilters', verbose_name='AR Filters')),
                ('parameter_settings', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_settings_geo_ar_challenge', to='challenges.ARChallengeParameterSettings')),
                ('sponsor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_geo_ar', to='challenges.Sponsor')),
            ],
            options={
                'verbose_name': 'Geo AR Challenge',
                'verbose_name_plural': 'Geo AR Challenges',
            },
        ),
        migrations.AlterModelOptions(
            name='geoarstar',
            options={'verbose_name': 'Geo AR Star', 'verbose_name_plural': 'Geo AR Stars'},
        ),
        migrations.RemoveField(
            model_name='geoarsite',
            name='list_of_tips',
        ),
        migrations.RemoveField(
            model_name='geoarsite',
            name='specific_tips',
        ),
        migrations.RemoveField(
            model_name='geoarstar',
            name='points',
        ),
        migrations.RemoveField(
            model_name='geolocation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='uniquechallengesite',
            name='challenges',
        ),
        migrations.AddField(
            model_name='uniquechallengesite',
            name='visibility_radius',
            field=models.IntegerField(default=0, verbose_name='Visibility Radius in Meters'),
        ),
        migrations.DeleteModel(
            name='Resource3dModel',
        ),
        migrations.AddField(
            model_name='geoarstar',
            name='challenges',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='challenges_geo_ar_star_site', to='challenges.GeoARChallenges', verbose_name='Geo Challenge Name'),
        ),
        migrations.AddField(
            model_name='uniquechallengesite',
            name='challenge',
            field=models.ManyToManyField(default=None, related_name='challenges_geo_ar_unique_site', to='challenges.GeoARChallenges', verbose_name='Geo Challenge Name'),
        ),
    ]
