# Generated by Django 2.2.28 on 2024-05-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0051_auto_20240517_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='sequence_number',
            field=models.IntegerField(default=0, verbose_name='Sequence Number'),
        ),
    ]
