# Generated by Django 2.2.28 on 2024-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0052_geolocation_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='image_recognition_file',
            field=models.FileField(blank=True, null=True, upload_to='ar_ir/img/', verbose_name='Image Recognition File'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='map_latitude_delta',
            field=models.DecimalField(decimal_places=2, default=0.0922, max_digits=5, verbose_name='Map Initial Longitude Delta'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='map_longitude_delta',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Map Initial Longitude Delta'),
        ),
    ]
