# Generated by Django 2.2.28 on 2024-05-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0053_auto_20240522_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='map_latitude_delta',
            field=models.DecimalField(decimal_places=4, default=0.0922, max_digits=6, verbose_name='Map Initial Longitude Delta'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='map_longitude_delta',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Map Initial Longitude Delta'),
        ),
    ]
