# Generated by Django 2.2.28 on 2024-05-22 15:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0054_auto_20240522_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('latitude_longitude', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geo Location')),
                ('map_longitude_delta', models.DecimalField(decimal_places=4, default=1, max_digits=6, verbose_name='Map Initial Longitude Delta')),
                ('map_latitude_delta', models.DecimalField(decimal_places=4, default=0.0922, max_digits=6, verbose_name='Map Initial Longitude Delta')),
            ],
            options={
                'verbose_name': 'Geo Region',
                'verbose_name_plural': 'Geo Regions',
            },
        ),
        migrations.AddField(
            model_name='geolocation',
            name='regions',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='geo_location_region', to='challenges.GeoRegion', verbose_name='AR Regions'),
        ),
    ]
