# Generated by Django 2.2.28 on 2024-05-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0055_auto_20240522_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarchallenges',
            name='challenge_choice',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('3DMODEL', '3D MODEL')], default='3DMODEL', max_length=50, verbose_name='Challenge Load From'),
        ),
        migrations.RemoveField(
            model_name='geoarchallenges',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='geoarchallenges',
            name='sponsor',
            field=models.ManyToManyField(default=None, related_name='sponsors_geo_ar', to='challenges.Sponsor', verbose_name='Sponsors'),
        ),
    ]
