# Generated by Django 2.2.28 on 2024-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0056_auto_20240528_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='ar_filters',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='filter_ar_challenge', to='challenges.ARChallengeFilters', verbose_name='AR Filters'),
        ),
        migrations.AlterField(
            model_name='geoarchallenges',
            name='ar_filters',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='filter_geo_ar_challenge', to='challenges.ARChallengeFilters', verbose_name='AR Filters'),
        ),
    ]
