# Generated by Django 2.2.28 on 2024-05-30 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0057_auto_20240529_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoarchallenges',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='geoarchallenges',
            name='sponsor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors_geo_ar', to='challenges.Sponsor'),
        ),
    ]
