# Generated by Django 2.2.28 on 2024-05-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0058_auto_20240530_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquechallengesite',
            name='lat_long',
        ),
        migrations.RemoveField(
            model_name='uniquechallengesite',
            name='visibility_radius',
        ),
    ]
