# Generated by Django 2.2.28 on 2024-06-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0059_auto_20240530_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarsite',
            name='check_ins',
            field=models.IntegerField(default=0, verbose_name='Check Ins'),
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='pin_challenge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='challenge_geo_ar_pin_site', to='challenges.GeoARChallenges', verbose_name='Geo Pin Challenge Name'),
        ),
    ]
