# Generated by Django 2.2.28 on 2024-06-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0060_auto_20240605_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarsite',
            name='check_ins_radius',
            field=models.IntegerField(default=50, verbose_name='Check Ins Radius in Meters'),
        ),
    ]
