# Generated by Django 2.2.28 on 2024-06-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0061_geoarsite_check_ins_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='aruserprofile',
            name='check_ins',
            field=models.BigIntegerField(default=0, verbose_name='Check-ins'),
        ),
        migrations.AlterField(
            model_name='geoarsite',
            name='check_ins',
            field=models.IntegerField(default=0, verbose_name='Check-ins'),
        ),
        migrations.AlterField(
            model_name='geoarsite',
            name='check_ins_radius',
            field=models.IntegerField(default=50, verbose_name='Check-ins Radius in Meters'),
        ),
    ]
