# Generated by Django 2.2.28 on 2024-06-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0062_auto_20240605_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoarchallenges',
            name='ar_filters',
        ),
    ]
