# Generated by Django 2.2.28 on 2024-06-05 20:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0063_remove_geoarchallenges_ar_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarstar',
            name='fun_facts',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Fun Facts'),
        ),
    ]
