# Generated by Django 2.2.28 on 2024-06-06 09:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0064_auto_20240605_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarstar',
            name='star_location',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326, verbose_name='Star Location'),
        ),
    ]
