# Generated by Django 2.2.28 on 2024-06-06 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0065_auto_20240606_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name')),
                ('collected_stars', models.IntegerField(default=0, verbose_name='Collected Stars')),
                ('geo_ar_star', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_star_collect_ar_star', to='challenges.GeoARStar')),
                ('geo_site', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_star_collect_ar_site', to='challenges.GeoArSite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ar_site_star', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geo AR Star Collections',
                'verbose_name_plural': 'Geo AR Star Collections',
            },
        ),
        migrations.CreateModel(
            name='GeoARSiteActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('geo_site', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_acitivity_ar_site', to='challenges.GeoArSite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ar_site_acitivity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geo AR Site Activity',
                'verbose_name_plural': 'Geo AR Site Activities',
            },
        ),
    ]
