# Generated by Django 2.2.28 on 2024-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0066_geoarsiteactivity_starcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarsite',
            name='address_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Address Text'),
        ),
    ]
