# Generated by Django 2.2.28 on 2024-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0067_geoarsite_address_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='challenge_choice',
            field=models.CharField(choices=[('SPONSORED', 'IMAGE'), ('DANCE', '3D MODEL')], default='DANCE', max_length=50, verbose_name='Challenge Load From'),
        ),
    ]
