# Generated by Django 2.2.28 on 2024-06-10 16:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0068_auto_20240610_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarsite',
            name='geo_site_border',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Geo Site Border'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='map_latitude_delta',
            field=models.DecimalField(decimal_places=4, default=0.0922, max_digits=6, verbose_name='Map Initial Latitude Delta'),
        ),
        migrations.AlterField(
            model_name='georegion',
            name='map_latitude_delta',
            field=models.DecimalField(decimal_places=4, default=0.0922, max_digits=6, verbose_name='Map Initial Latitude Delta'),
        ),
    ]
