# Generated by Django 2.2.28 on 2024-06-10 16:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0069_auto_20240610_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarsite',
            name='geo_site_border',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326, verbose_name='Geo Site Line'),
        ),
    ]
