# Generated by Django 2.2.28 on 2024-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0070_auto_20240610_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarstar',
            name='sponsors',
            field=models.ManyToManyField(related_name='ar_stars_sponsored', to='challenges.Sponsor', verbose_name='Sponsors'),
        ),
    ]
