# Generated by Django 2.2.28 on 2024-06-11 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0071_geoarstar_sponsors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARSitePinCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_image', models.ImageField(blank=True, null=True, upload_to='geoar/checkinimg/')),
                ('approval', models.CharField(blank=True, choices=[('UNAPPROVED', 'APPROVED BUT NOT REVIEWED'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='UNAPPROVED', max_length=50, null=True)),
                ('declined_reason', models.TextField(blank=True, null=True, verbose_name='Declined Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geo_site', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_star_checkin_ar_site', to='challenges.GeoArSite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ar_site_checkin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AR Site Pin Check-ins',
            },
        ),
    ]
