# Generated by Django 2.2.28 on 2024-06-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0072_arsitepincheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='armemories',
            name='geo_challenge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_challenges_ar_memories', to='challenges.GeoARChallenges', verbose_name='Geo Challenge'),
        ),
        migrations.AlterField(
            model_name='armemories',
            name='challenges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_ar_memories', to='challenges.Challenges', verbose_name='Challenge'),
        ),
    ]
