# Generated by Django 2.2.28 on 2024-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0073_auto_20240611_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoarsite',
            name='check_ins_radius',
        ),
        migrations.RemoveField(
            model_name='geoarsite',
            name='geo_site_area',
        ),
        migrations.AlterField(
            model_name='geoarsite',
            name='address_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Address Text'),
        ),
    ]
