# Generated by Django 2.2.28 on 2024-06-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0074_auto_20240611_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='ar_filters',
            field=models.ManyToManyField(blank=True, default=None, related_name='filter_ar_challenge', to='challenges.ARChallengeFilters', verbose_name='AR Filters'),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='regions',
            field=models.ManyToManyField(blank=True, default=None, related_name='geo_location_region', to='challenges.GeoRegion', verbose_name='AR Regions'),
        ),
    ]
