# Generated by Django 2.2.28 on 2024-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0075_auto_20240611_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archallengefilters',
            name='filter_text',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Filter Text'),
        ),
        migrations.AlterField(
            model_name='archallengefilters',
            name='filter_text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=10, null=True, verbose_name='Filter Text Color'),
        ),
        migrations.AlterField(
            model_name='archallengefilters',
            name='filter_text_size',
            field=models.CharField(blank=True, default='22', max_length=10, null=True, verbose_name='Filter Text Size'),
        ),
    ]
