# Generated by Django 2.2.28 on 2024-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0076_auto_20240612_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexample',
            name='any_where_challenges',
            field=models.ManyToManyField(blank=True, default=None, related_name='ar_example_challenge', to='challenges.Challenges', verbose_name='Any Where AR Challenges'),
        ),
        migrations.AddField(
            model_name='arexample',
            name='geo_challenges',
            field=models.ManyToManyField(blank=True, default=None, related_name='geo_ar_example_challenge', to='challenges.GeoARChallenges', verbose_name='Geo AR Challenges'),
        ),
    ]
