# Generated by Django 2.2.28 on 2024-06-13 10:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0077_auto_20240612_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquechallengesite',
            name='latitude_longitude',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geo Location'),
        ),
        migrations.AddField(
            model_name='uniquechallengesite',
            name='visibility_radius',
            field=models.IntegerField(default=10, verbose_name='Visibility Radius in Meters'),
        ),
        migrations.AlterField(
            model_name='geoarstar',
            name='visibility_radius',
            field=models.IntegerField(default=10, verbose_name='Visibility Radius in Meters'),
        ),
    ]
