# Generated by Django 2.2.28 on 2024-06-14 16:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0078_auto_20240613_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starcollection',
            name='collected_stars',
        ),
        migrations.AddField(
            model_name='starcollection',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point'),
        ),
    ]
