# Generated by Django 2.2.28 on 2024-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0079_auto_20240614_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='archallengefilters',
            name='app_name_text',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='App Name Text'),
        ),
        migrations.AddField(
            model_name='archallengefilters',
            name='app_name_text_color',
            field=models.CharField(default='#ffffff', max_length=10, verbose_name='App Name Text Color'),
        ),
        migrations.AddField(
            model_name='archallengefilters',
            name='app_name_text_size',
            field=models.CharField(default='14', max_length=10, verbose_name='App Name Text Size'),
        ),
    ]
