# Generated by Django 2.2.28 on 2024-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0080_auto_20240624_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='archallengefilters',
            name='text_form_image',
            field=models.BooleanField(default=False, verbose_name='Load Image Text'),
        ),
        migrations.AlterField(
            model_name='archallengefilters',
            name='app_name_text',
            field=models.CharField(blank=True, default='ROAM REALITY', max_length=200, null=True, verbose_name='App Name Text'),
        ),
    ]
