# Generated by Django 2.2.28 on 2024-06-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0081_auto_20240624_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarsite',
            name='sponsors',
            field=models.ManyToManyField(related_name='ar_sites_sponsored', to='challenges.Sponsor', verbose_name='Sponsors'),
        ),
    ]
