# Generated by Django 2.2.28 on 2024-06-25 20:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0082_geoarsite_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='georegion',
            name='geo_region',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326, verbose_name='Geo Region'),
        ),
    ]
