# Generated by Django 2.2.28 on 2024-06-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0083_georegion_geo_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='georegion',
            name='latitude_longitude',
        ),
        migrations.RemoveField(
            model_name='georegion',
            name='map_latitude_delta',
        ),
        migrations.RemoveField(
            model_name='georegion',
            name='map_longitude_delta',
        ),
    ]
