# Generated by Django 2.2.28 on 2024-06-26 12:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0084_auto_20240626_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='border',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326, verbose_name='Borders'),
        ),
    ]
