# Generated by Django 2.2.28 on 2024-06-28 13:01

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0085_geolocation_border'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoARGoldStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='geoargoldstar/img/')),
                ('star_location', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326, verbose_name='Star Location')),
                ('fun_facts', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Fun Facts')),
                ('visibility_radius', models.IntegerField(default=10, verbose_name='Visibility Radius in Meters')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('geo_site', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_ar_goldstar_ar_site', to='challenges.GeoArSite')),
                ('sponsors', models.ManyToManyField(related_name='ar_gold_stars_sponsored', to='challenges.Sponsor', verbose_name='Sponsors')),
            ],
            options={
                'verbose_name': 'Geo AR Gold Star',
                'verbose_name_plural': 'Geo AR Gold Stars',
            },
        ),
    ]
