# Generated by Django 2.2.28 on 2024-06-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0086_geoargoldstar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoargoldstar',
            name='geo_site',
        ),
        migrations.AddField(
            model_name='geoargoldstar',
            name='geo_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_location_ar_gold_star', to='challenges.GeoLocation'),
        ),
    ]
