# Generated by Django 2.2.28 on 2024-06-29 20:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0087_auto_20240628_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='aruserprofile',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Current Location'),
        ),
    ]
