# Generated by Django 2.2.28 on 2024-06-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0088_aruserprofile_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='geoar/img-flag/', verbose_name='Flag Scoreboard'),
        ),
    ]
