# Generated by Django 2.2.28 on 2024-07-02 11:42

import ckeditor.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0089_geolocation_flag_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='geoargoldstar/img/')),
                ('facts', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Facts')),
                ('visibility_radius', models.IntegerField(default=10, verbose_name='Visibility Radius in Meters')),
                ('location', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('geo_location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_location_ar_facts', to='challenges.GeoLocation')),
                ('sponsors', models.ManyToManyField(related_name='ar_destination_facts_sponsored', to='challenges.Sponsor', verbose_name='Sponsors')),
            ],
            options={
                'verbose_name': 'Geo Destination Fact',
                'verbose_name_plural': 'Geo Destination Facts',
            },
        ),
    ]
