# Generated by Django 2.2.28 on 2024-07-04 10:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0090_destinationfacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='bloom_threshold',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Bloom Threshold'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='diffuse_intensity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Diffuse Intensity'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='diffuse_text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=10, null=True, verbose_name='Diffuse Color'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='max_pinch_scale',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Maximum Zoom Scaling'),
        ),
    ]
