# Generated by Django 2.2.28 on 2024-07-04 11:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0092_panicmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationfacts',
            name='location',
        ),
        migrations.RemoveField(
            model_name='destinationfacts',
            name='visibility_radius',
        ),
        migrations.AddField(
            model_name='destinationfacts',
            name='border',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326, verbose_name='Borders'),
        ),
    ]
