# Generated by Django 2.2.28 on 2024-07-04 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0093_auto_20240704_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panicmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_panic_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
