# Generated by Django 2.2.28 on 2024-07-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0094_auto_20240704_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoargoldstar',
            name='geo_site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_ar_goldstar_ar_site', to='challenges.GeoArSite', verbose_name='Geo Site'),
        ),
        migrations.AlterField(
            model_name='geoargoldstar',
            name='geo_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_location_ar_gold_star', to='challenges.GeoLocation', verbose_name='Geo Destination'),
        ),
    ]
