# Generated by Django 2.2.28 on 2024-07-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0095_auto_20240704_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panicmessage',
            options={'verbose_name': 'Panic Message', 'verbose_name_plural': 'Panic Messages'},
        ),
    ]
