# Generated by Django 2.2.28 on 2024-07-10 13:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0096_auto_20240704_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='panicmessage',
            name='location',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
    ]
