# Generated by Django 2.2.28 on 2024-07-18 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0098_auto_20240710_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarsite',
            name='geo_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='geo_location_ar_site', to='challenges.GeoLocation', verbose_name='Geo Destination'),
        ),
    ]
