# Generated by Django 2.2.28 on 2024-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0099_auto_20240718_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarsite',
            name='image',
            field=models.ImageField(default=None, upload_to='geoar/img/'),
        ),
    ]
