# Generated by Django 2.2.28 on 2024-07-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0100_auto_20240730_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoarsite',
            name='sponsors',
        ),
    ]
