# Generated by Django 2.2.28 on 2024-08-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0101_remove_geoarsite_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archallengefilters',
            name='location_option',
            field=models.CharField(choices=[('COUNTRY_ONLY', 'COUNTRY ONLY'), ('SITE_ONLY', 'SITE + COUNTRY'), ('SITE_COUNTRY', 'SITE + COUNTRY')], default='COUNTRY_ONLY', max_length=50, verbose_name='Location Text'),
        ),
    ]
