# Generated by Django 2.2.28 on 2024-09-06 18:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0103_auto_20240813_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archallengefilters',
            options={'ordering': ['name'], 'verbose_name': 'AR Filter', 'verbose_name_plural': 'AR Filters'},
        ),
        migrations.AddField(
            model_name='challenges',
            name='scale',
            field=models.DecimalField(decimal_places=10, default=0.05, max_digits=20),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='scale_object',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('8.00'))], verbose_name='Object Scale'),
        ),
    ]
