# Generated by Django 2.2.28 on 2024-09-07 22:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0104_auto_20240906_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='scale',
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='scale_object',
            field=models.DecimalField(decimal_places=5, default=0.05, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('8.00'))], verbose_name='Object Scale'),
        ),
    ]
