# Generated by Django 2.2.28 on 2024-09-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0105_auto_20240907_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenges',
            options={'verbose_name': 'AR Challenge', 'verbose_name_plural': 'AR Challenge'},
        ),
        migrations.RemoveField(
            model_name='arexample',
            name='image',
        ),
        migrations.RemoveField(
            model_name='arexample',
            name='video_file',
        ),
        migrations.CreateModel(
            name='ARExampleVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='ar/example/')),
                ('ar_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='challenges.ARExample')),
            ],
        ),
        migrations.CreateModel(
            name='ARExampleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ar/example/')),
                ('ar_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='challenges.ARExample')),
            ],
        ),
    ]
