# Generated by Django 2.2.28 on 2024-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0105_auto_20240907_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarsite',
            name='check_in_site_radius',
            field=models.IntegerField(default=50, verbose_name='Check-in Site Radius'),
        ),
    ]
