# Generated by Django 2.2.28 on 2024-09-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0106_geoarsite_check_in_site_radius'),
        ('challenges', '0106_auto_20240925_1330'),
    ]

    operations = [
    ]
