# Generated by Django 2.2.28 on 2024-10-29 20:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0107_merge_20240926_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archallengeparametersettings',
            name='bloom',
        ),
        migrations.RemoveField(
            model_name='archallengeparametersettings',
            name='pinch_to_zoom',
        ),
        migrations.RemoveField(
            model_name='archallengeparametersettings',
            name='rotation',
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='bloom_intensity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Bloom Intensity'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='emission_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Emission Value'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='isRotationEnabled',
            field=models.BooleanField(default=True, verbose_name='Rotation Enabled'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='rotation_speed',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rotation Speed'),
        ),
        migrations.AddField(
            model_name='archallengeparametersettings',
            name='scale_speed',
            field=models.DecimalField(decimal_places=4, default=0.0015, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('1.0000'))], verbose_name='Scale Speed'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='ar_portals',
            field=models.BooleanField(default=False, editable=False, verbose_name='AR Portals'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='diffuse_intensity',
            field=models.DecimalField(decimal_places=2, default=1.0, editable=False, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Diffuse Intensity'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='diffuse_text_color',
            field=models.CharField(blank=True, default='#ffffff', editable=False, max_length=10, null=True, verbose_name='Diffuse Color'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='image_opacity',
            field=models.BooleanField(default=False, editable=False, verbose_name='Image Opacity'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='image_opacity_value',
            field=models.DecimalField(decimal_places=2, default=1.0, editable=False, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Image Opacity Value'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='image_recognition',
            field=models.BooleanField(default=False, editable=False, verbose_name='Image Recognition'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='image_recognition_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='ar_ir/img/', verbose_name='Image Recognition File'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='loop_animations',
            field=models.BooleanField(default=False, editable=False, verbose_name='Loop Animation'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='loop_delay',
            field=models.IntegerField(default=1000, editable=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loop Delay'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='max_pinch_scale',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('3.00'))], verbose_name='Maximum Zoom Scaling'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='min_pinch_scale',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))], verbose_name='Minimum Zoom Scaling'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='scale_object',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('8.00'))], verbose_name='Object Scale'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='tracking_and_anchors',
            field=models.BooleanField(default=False, editable=False, verbose_name='Tracking and Anchors'),
        ),
    ]
