# Generated by Django 2.2.28 on 2024-11-07 12:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0108_auto_20241029_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='bloom_intensity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))], verbose_name='Bloom Intensity'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='bloom_threshold',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-1.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Bloom Threshold'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='emission_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))], verbose_name='Emission Value'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='max_pinch_scale',
            field=models.DecimalField(decimal_places=3, default=3.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('3.000'))], verbose_name='Maximum Zoom Scaling'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='min_pinch_scale',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.000')), django.core.validators.MaxValueValidator(Decimal('1.000'))], verbose_name='Minimum Zoom Scaling'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='positionX',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Position X'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='positionY',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Position Y'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='positionZ',
            field=models.DecimalField(decimal_places=3, default=-0.4, max_digits=6, verbose_name='Position Z'),
        ),
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='scale_speed',
            field=models.DecimalField(decimal_places=4, default=0.0015, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('10.0000'))], verbose_name='Scale Speed'),
        ),
    ]
