# Generated by Django 2.2.28 on 2024-12-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0109_auto_20241107_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arsitepincheckin',
            old_name='approval',
            new_name='challenge_approval',
        ),
        migrations.AddField(
            model_name='arsitepincheckin',
            name='challenges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_ar_check_in', to='challenges.Challenges', verbose_name='Challenge'),
        ),
    ]
