# Generated by Django 2.2.28 on 2024-12-16 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0110_auto_20241206_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Info'),
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Info'),
        ),
        migrations.AddField(
            model_name='geoarstar',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Info'),
        ),
    ]
