# Generated by Django 2.2.28 on 2024-12-18 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0111_auto_20241216_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arsitepincheckin',
            old_name='check_in_image',
            new_name='memory_file',
        ),
        migrations.RemoveField(
            model_name='arsitepincheckin',
            name='challenges',
        ),
        migrations.AddField(
            model_name='armemories',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='arsitepincheckin',
            name='geo_challenge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_challenges_ar_check_in', to='challenges.GeoARChallenges', verbose_name='Geo Challenge'),
        ),
        migrations.AddField(
            model_name='arsitepincheckin',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
    ]
