# Generated by Django 2.2.28 on 2024-12-18 17:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0111_auto_20241216_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoarstar',
            name='star_location',
        ),
        migrations.AddField(
            model_name='geoarstar',
            name='following_mode',
            field=models.CharField(choices=[('PROXIMITY', 'BY PROXIMITY'), ('SPECIFIC', 'SPECIFIC ORDER')], default='PROXIMITY', max_length=20, verbose_name='Star Following Mode'),
        ),
        migrations.CreateModel(
            name='GeoARStarPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Star Location')),
                ('order', models.PositiveIntegerField(default=0, help_text="Order of the star when following mode is 'SPECIFIC ORDER'")),
                ('geo_ar_star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='challenges.GeoARStar')),
            ],
        ),
    ]
