# Generated by Django 2.2.28 on 2024-12-19 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0112_auto_20241218_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoarstarpoint',
            options={'verbose_name': 'Geo AR Star Point', 'verbose_name_plural': 'Geo AR Star Points'},
        ),
        migrations.AddField(
            model_name='starcollection',
            name='geo_ar_star_point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_star_collect_ar_star_point', to='challenges.GeoARStarPoint'),
        ),
    ]
