# Generated by Django 2.2.28 on 2024-12-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0113_auto_20241219_0046'),
        ('challenges', '0112_auto_20241218_2047'),
    ]

    operations = [
    ]
