# Generated by Django 2.2.28 on 2025-01-03 17:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0114_merge_20241219_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarchallenges',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Info'),
        ),
    ]
