# Generated by Django 2.2.28 on 2025-01-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0115_geoarchallenges_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='cooldown_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Cooldown (in hours)'),
        ),
        migrations.AddField(
            model_name='geoarchallenges',
            name='cooldown_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Cooldown (in hours)'),
        ),
    ]
