# Generated by Django 2.2.28 on 2025-01-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0116_auto_20250122_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARExperienceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('color', models.CharField(blank=True, default='#ffffff', max_length=10, null=True, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='ARExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(default=None, max_length=255, verbose_name='Title 1')),
                ('title_2', models.CharField(default=None, max_length=255, verbose_name='Title 2')),
                ('subtitle', models.CharField(default=None, max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ar/img/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('categories', models.ManyToManyField(null=True, related_name='experiences', to='challenges.ARExperienceCategory')),
            ],
            options={
                'verbose_name': 'AR Experience',
                'verbose_name_plural': 'AR Experiences',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='challenges',
            name='ar_experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='challenges.ARExperience'),
        ),
        migrations.AddField(
            model_name='geoarchallenges',
            name='ar_experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_challenges', to='challenges.ARExperience'),
        ),
    ]
