# Generated by Django 2.2.28 on 2025-01-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0117_auto_20250123_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperience',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='challenges.ARExperienceCategory'),
        ),
    ]
