# Generated by Django 2.2.28 on 2025-01-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0118_auto_20250123_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ARExperienceCategory',
            new_name='GeoArSiteCategory',
        ),
        migrations.AlterModelOptions(
            name='geoarsitecategory',
            options={'verbose_name': 'Geo AR Site Category', 'verbose_name_plural': 'Geo AR Site Categories'},
        ),
        migrations.RemoveField(
            model_name='arexperience',
            name='categories',
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_sites', to='challenges.GeoArSiteCategory', verbose_name='Geo Site Category'),
        ),
    ]
