# Generated by Django 2.2.28 on 2025-01-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0119_auto_20250124_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperience',
            name='subtitle',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='arexperience',
            name='title_2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Title 2'),
        ),
    ]
