# Generated by Django 2.2.28 on 2025-01-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0120_auto_20250124_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexperience',
            name='is_event',
            field=models.BooleanField(default=False, verbose_name='Is event'),
        ),
    ]
