# Generated by Django 2.2.28 on 2025-01-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0121_arexperience_is_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexperience',
            name='geo_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_experiences', to='challenges.GeoLocation', verbose_name='Geo Destination'),
        ),
    ]
