# Generated by Django 2.2.28 on 2025-01-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0122_arexperience_geo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arexperience',
            name='is_event',
        ),
        migrations.AddField(
            model_name='arexperience',
            name='experience_type',
            field=models.CharField(choices=[('AR_CHALLENGE', 'AR CHALLENGE'), ('GEO_AR_CHALLENGE', 'GEO AR CHALLENGE'), ('EVENT', 'EVENT')], default='AR_CHALLENGE', max_length=20, verbose_name='Experience type'),
        ),
    ]
