# Generated by Django 2.2.28 on 2025-01-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0123_auto_20250129_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoarchallenges',
            name='challenge_attempt',
        ),
        migrations.RemoveField(
            model_name='geoarchallenges',
            name='cooldown_hours',
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='challenge_attempt',
            field=models.IntegerField(default=1, verbose_name='Challenge Attempts'),
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='cooldown_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Cooldown (in hours)'),
        ),
    ]
