# Generated by Django 2.2.28 on 2025-01-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0124_auto_20250130_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenges',
            options={'ordering': ['order'], 'verbose_name': 'AR Challenge', 'verbose_name_plural': 'AR Challenge'},
        ),
        migrations.AddField(
            model_name='challenges',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
