# Generated by Django 2.2.28 on 2025-02-05 12:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0125_auto_20250131_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarsite',
            name='sponsor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_site', to='challenges.Sponsor'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tags (optional)'),
        ),
    ]
