# Generated by Django 2.2.28 on 2025-02-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0126_auto_20250205_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarchallenges',
            name='color',
            field=models.CharField(blank=True, default='#ffffff', max_length=10, null=True, verbose_name='Color'),
        ),
    ]
