# Generated by Django 2.2.28 on 2025-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0127_geoarchallenges_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexperience',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
