# Generated by Django 2.2.28 on 2025-02-12 14:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0128_arexperience_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archallengeparametersettings',
            name='rotation_speed',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(1)], verbose_name='Rotation Speed'),
        ),
    ]
