# Generated by Django 2.2.28 on 2025-02-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0128_arexperience_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
