# Generated by Django 2.2.28 on 2025-02-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0129_auto_20250210_2001'),
        ('challenges', '0129_auto_20250212_1430'),
    ]

    operations = [
    ]
