# Generated by Django 2.2.28 on 2025-02-20 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0130_merge_20250217_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarsite',
            name='band_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_site', to=settings.AUTH_USER_MODEL),
        ),
    ]
