# Generated by Django 2.2.28 on 2025-02-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0130_merge_20250217_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='armemories',
            name='geo_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_memories', to='challenges.GeoLocation', verbose_name='Geo Destination'),
        ),
    ]
