# Generated by Django 2.2.28 on 2025-02-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0131_armemories_geo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsitepincheckin',
            name='geo_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_checkins', to='challenges.GeoLocation', verbose_name='Geo Destination'),
        ),
    ]
