# Generated by Django 2.2.28 on 2025-02-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0132_arsitepincheckin_geo_location'),
        ('challenges', '0131_geoarsite_band_user'),
    ]

    operations = [
    ]
