# Generated by Django 2.2.28 on 2025-02-21 19:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0133_merge_20250221_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='band_borders',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326, verbose_name='Band Borders'),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='event_borders',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326, verbose_name='Event Borders'),
        ),
    ]
