# Generated by Django 2.2.28 on 2025-02-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0134_auto_20250221_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperience',
            name='experience_type',
            field=models.CharField(choices=[('AR_CHALLENGE', 'AR CHALLENGE'), ('GEO_AR_CHALLENGE', 'GEO AR CHALLENGE'), ('EVENT', 'EVENT'), ('BAND', 'BAND')], default='AR_CHALLENGE', max_length=20, verbose_name='Experience type'),
        ),
    ]
