# Generated by Django 2.2.28 on 2025-03-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0135_auto_20250225_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='aruserprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
