# Generated by Django 2.2.28 on 2025-03-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0136_aruserprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
