# Generated by Django 2.2.28 on 2025-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0137_geolocation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='allow_upload_image',
            field=models.BooleanField(default=True, verbose_name='Allow Upload Image'),
        ),
    ]
