# Generated by Django 2.2.28 on 2025-06-27 12:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0138_challenges_allow_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarstarpoint',
            name='elevation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='geoarstarpoint',
            name='fun_facts',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Fun Facts'),
        ),
    ]
