# Generated by Django 2.2.28 on 2025-07-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0139_auto_20250627_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARUserProfileScoreboard',
            fields=[
            ],
            options={
                'verbose_name': 'Scoreboard',
                'verbose_name_plural': 'Scoreboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('challenges.aruserprofile',),
        ),
        migrations.AlterField(
            model_name='armemories',
            name='memory_file',
            field=models.FileField(blank=True, null=True, upload_to='ar/memories/'),
        ),
    ]
