# Generated by Django 2.2.28 on 2025-07-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0140_auto_20250702_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarstarpoint',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='ar/geo_star_point/'),
        ),
    ]
