# Generated by Django 2.2.28 on 2025-07-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0141_geoarstarpoint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='armemories',
            name='sponsor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_memories', to='challenges.Sponsor'),
        ),
        migrations.AlterField(
            model_name='armemories',
            name='declined_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='armemories',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('BONUS', 'BONUS'), ('DEDUCTED', 'DEDUCTED')], default='PHOTO', max_length=50, null=True),
        ),
    ]
