# Generated by Django 2.2.28 on 2025-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0142_auto_20250703_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
