# Generated by Django 3.2.25 on 2025-07-08 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
        ('challenges', '0143_sponsor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archallengefilters',
            name='gradient_colors',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='ar_challenge_filters_gradient_colors', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Gradient Colours'),
        ),
        migrations.AlterField(
            model_name='armemories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_memories_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='arsitepincheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_site_pin_checkin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aruserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ar_user_profile_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geoarsite',
            name='band_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_ar_site_band_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geoarsiteactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_ar_site_activity_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='panicmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panic_message_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='starcollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_collection_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
