# Generated by Django 3.2.25 on 2025-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0144_auto_20250708_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarstarpoint',
            name='sponsors',
            field=models.ManyToManyField(related_name='stars', to='challenges.Sponsor'),
        ),
    ]
