# Generated by Django 3.2.25 on 2025-07-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0145_geoarstarpoint_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarstarpoint',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geoarstarpoint',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='stars', to='challenges.Sponsor'),
        ),
    ]
