# Generated by Django 3.2.25 on 2025-07-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0146_auto_20250714_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('file_image', models.ImageField(upload_to='scanpicture/img/')),
                ('file_animation', models.FileField(upload_to='scanpicture/animation/')),
            ],
        ),
        migrations.AddField(
            model_name='geoarsite',
            name='scan_pictures',
            field=models.ManyToManyField(blank=True, related_name='geo_sites', to='challenges.ScanPicture'),
        ),
    ]
