# Generated by Django 3.2.25 on 2025-07-23 19:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0147_auto_20250717_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpicture',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordinates'),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='file_3d',
            field=models.FileField(blank=True, null=True, upload_to='scanpicture/3d/', verbose_name='3D File'),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='scanpicture/icon/', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_pictures', to='challenges.sponsor'),
        ),
        migrations.AlterField(
            model_name='scanpicture',
            name='file_animation',
            field=models.FileField(upload_to='scanpicture/animation/', verbose_name='Animation'),
        ),
        migrations.AlterField(
            model_name='scanpicture',
            name='file_image',
            field=models.ImageField(upload_to='scanpicture/img/', verbose_name='Image'),
        ),
    ]
