# Generated by Django 3.2.25 on 2025-07-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0148_auto_20250723_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanpicture',
            name='file_image',
            field=models.ImageField(blank=True, null=True, upload_to='scanpicture/img/', verbose_name='Image'),
        ),
    ]
