# Generated by Django 3.2.25 on 2025-08-01 13:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0149_alter_scanpicture_file_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpicture',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Info'),
        ),
    ]
