# Generated by Django 3.2.25 on 2025-08-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0150_scanpicture_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarstar',
            name='attempts',
            field=models.IntegerField(default=1, verbose_name='Attempts'),
        ),
        migrations.AddField(
            model_name='geoarstar',
            name='cooldown_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Cooldown (in hours)'),
        ),
        migrations.AddField(
            model_name='geoarstarpoint',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='attempts',
            field=models.IntegerField(default=1, verbose_name='Attempts'),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='cooldown_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Cooldown (in hours)'),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
    ]
