# Generated by Django 3.2.25 on 2025-08-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0150_scanpicture_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='armemories',
            name='user_first_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arsitepincheckin',
            name='user_first_attempt',
            field=models.BooleanField(default=False),
        ),
    ]
