# Generated by Django 3.2.25 on 2025-08-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0151_auto_20250801_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armemories',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('STAR', 'STAR'), ('BONUS', 'BONUS'), ('DEDUCTED', 'DEDUCTED')], default='PHOTO', max_length=50, null=True),
        ),
    ]
