# Generated by Django 3.2.25 on 2025-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0151_auto_20250801_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarstar',
            name='attempts',
            field=models.IntegerField(default=1, verbose_name='Attempts'),
        ),
        migrations.AddField(
            model_name='geoarstar',
            name='cooldown_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Cooldown (in hours)'),
        ),
        migrations.AddField(
            model_name='geoarstarpoint',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='attempts',
            field=models.IntegerField(default=1, verbose_name='Attempts'),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='cooldown_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Cooldown (in hours)'),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='armemories',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('STAR', 'STAR'), ('BONUS', 'BONUS'), ('DEDUCTED', 'DEDUCTED')], default='PHOTO', max_length=50, null=True),
        ),
    ]
