# Generated by Django 3.2.25 on 2025-08-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0152_auto_20250804_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armemories',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('SCAN_PHOTO', 'SCAN_PHOTO'), ('STAR', 'STAR'), ('BONUS', 'BONUS'), ('DEDUCTED', 'DEDUCTED')], default='PHOTO', max_length=50, null=True),
        ),
    ]
