# Generated by Django 3.2.25 on 2025-08-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0153_alter_armemories_memory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='armemories',
            name='scan_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_memories', to='challenges.scanpicture', verbose_name='Scan picture'),
        ),
        migrations.AddField(
            model_name='armemories',
            name='star_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_memories', to='challenges.geoarstarpoint', verbose_name='Star point'),
        ),
    ]
