# Generated by Django 3.2.25 on 2025-08-04 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0154_auto_20250804_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='starcollection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
