# Generated by Django 3.2.25 on 2025-08-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0155_starcollection_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starcollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
