# Generated by Django 3.2.25 on 2025-08-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0156_alter_starcollection_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanpicture',
            options={'verbose_name': 'Scan', 'verbose_name_plural': 'Scans'},
        ),
        migrations.AlterField(
            model_name='armemories',
            name='scan_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ar_memories', to='challenges.scanpicture', verbose_name='Scans'),
        ),
    ]
