# Generated by Django 3.2.25 on 2025-08-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0157_auto_20250808_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarsite',
            name='scan_pictures',
            field=models.ManyToManyField(blank=True, related_name='geo_sites', to='challenges.ScanPicture', verbose_name='Scans'),
        ),
    ]
