# Generated by Django 3.2.25 on 2025-08-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0158_alter_geoarsite_scan_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarsite',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
