# Generated by Django 3.2.25 on 2025-08-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0159_auto_20250813_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanpicture',
            name='file_animation',
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='file_animation_android',
            field=models.FileField(blank=True, null=True, upload_to='scanpicture/animation_android/', verbose_name='Animation android'),
        ),
        migrations.AddField(
            model_name='scanpicture',
            name='file_animation_ios',
            field=models.FileField(blank=True, null=True, upload_to='scanpicture/animation_ios/', verbose_name='Animation ios'),
        ),
    ]
