# Generated by Django 3.2.25 on 2025-09-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0160_auto_20250813_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanpicture',
            name='file_animation_android',
            field=models.FileField(null=True, upload_to='scanpicture/animation_android/', verbose_name='Animation android'),
        ),
        migrations.AlterField(
            model_name='scanpicture',
            name='file_animation_ios',
            field=models.FileField(null=True, upload_to='scanpicture/animation_ios/', verbose_name='Animation ios'),
        ),
    ]
