# Generated by Django 3.2.25 on 2025-09-10 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0161_auto_20250910_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarstar',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='ar/geo_star/', verbose_name='3D Model'),
        ),
        migrations.AddField(
            model_name='geoarstar',
            name='parameter_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_ar_stars', to='challenges.archallengeparametersettings', verbose_name='Parameter Settings'),
        ),
    ]
