# Generated by Django 3.2.25 on 2025-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0162_auto_20250910_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarstarpoint',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
