# Generated by Django 3.2.25 on 2025-10-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0163_geoarstarpoint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armemories',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO'), ('SCAN_PHOTO', 'SCAN_PHOTO'), ('STAR', 'STAR'), ('BONUS', 'BONUS'), ('DEDUCTED', 'DEDUCTED'), ('SOCIAL_POINTS', 'SOCIAL_POINTS')], default='PHOTO', max_length=50, null=True),
        ),
    ]
