# Generated by Django 3.2.25 on 2025-10-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0164_alter_armemories_memory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARChallengeDesigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'AR Challenge Design',
                'verbose_name_plural': 'AR Challenge Designs',
            },
        ),
    ]
