# Generated by Django 3.2.25 on 2025-10-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0165_archallengedesigns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ARChallengeDesigns',
            new_name='ARChallengeModels',
        ),
        migrations.AlterModelOptions(
            name='archallengemodels',
            options={'verbose_name': 'AR Challenge Models', 'verbose_name_plural': 'AR Challenge Models'},
        ),
        migrations.AlterModelTable(
            name='archallengemodels',
            table='ar_challenge_models',
        ),
    ]
