# Generated by Django 3.2.25 on 2025-10-14 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0166_auto_20251014_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='archallengemodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 14, 10, 37, 30, 217384, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archallengemodels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ar/img/'),
        ),
        migrations.AddField(
            model_name='archallengemodels',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='ar/model/'),
        ),
    ]
