# Generated by Django 3.2.25 on 2025-10-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0167_auto_20251014_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='armemories',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Control whether this memory is public or private', max_length=10),
        ),
    ]
