# Generated by Django 3.2.25 on 2025-10-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0170_remove_geoarstar_model_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexample',
            name='geo_ar_scan',
            field=models.ManyToManyField(blank=True, default=None, related_name='geo_ar_scan', to='challenges.ScanPicture', verbose_name='Geo AR ScanPicture'),
        ),
    ]
