# Generated by Django 3.2.25 on 2025-10-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0171_arexample_geo_ar_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexample',
            name='geo_ar_hunt_point',
            field=models.ManyToManyField(blank=True, default=None, related_name='geo_ar_hunt_point', to='challenges.GeoARStarPoint', verbose_name='Geo AR Hunt Point'),
        ),
        migrations.AlterField(
            model_name='arexample',
            name='geo_ar_scan',
            field=models.ManyToManyField(blank=True, default=None, related_name='geo_ar_scan', to='challenges.ScanPicture', verbose_name='Geo AR Scan'),
        ),
    ]
