# Generated by Django 3.2.25 on 2025-10-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0172_auto_20251022_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoarstar',
            options={'verbose_name': 'Geo AR Hunts', 'verbose_name_plural': 'Geo AR Hunts'},
        ),
        migrations.AlterModelOptions(
            name='geoarstarpoint',
            options={'verbose_name': 'Geo AR Hunt Point', 'verbose_name_plural': 'Geo AR Hunt Points'},
        ),
    ]
