# Generated by Django 3.2.25 on 2025-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0173_auto_20251022_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arexample',
            name='geo_ar_hunt_point',
        ),
        migrations.AddField(
            model_name='arexample',
            name='geo_ar_hunt',
            field=models.ManyToManyField(blank=True, default=None, related_name='geo_ar_hunt', to='challenges.GeoARStar', verbose_name='Geo AR Hunt'),
        ),
    ]
