# Generated by Django 3.2.25 on 2025-12-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0174_auto_20251023_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpicture',
            name='parameter_settings',
            field=models.ForeignKey(
                blank=True,
                null=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='parameter_settings_scan_picture',
                to='challenges.archallengeparametersettings',
                verbose_name='Parameter Settings'
            ),
        ),
    ]

