# Generated by Django 3.2.25 on 2025-10-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0175_add_parameter_settings_to_scanpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoarstarpoint',
            name='elevation',
            field=models.IntegerField(blank=True, help_text='Elevation for this AR point', null=True, verbose_name='Elevation'),
        ),
    ]
