# Generated by Django 3.2.25 on 2025-10-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0178_geoarstarpoint_screen_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanpicture',
            name='file_animation_android',
            field=models.FileField(blank=True, null=True, upload_to='scanpicture/animation_android/', verbose_name='Animation android'),
        ),
        migrations.AlterField(
            model_name='scanpicture',
            name='file_animation_ios',
            field=models.FileField(blank=True, null=True, upload_to='scanpicture/animation_ios/', verbose_name='Animation ios'),
        ),
    ]
