# Generated by Django 3.2.25 on 2025-11-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0179_auto_20251030_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoarstarpoint',
            name='model_file',
        ),
        migrations.RemoveField(
            model_name='scanpicture',
            name='file_3d',
        ),
        migrations.AddField(
            model_name='geoarstarpoint',
            name='file_animation_android',
            field=models.FileField(blank=True, null=True, upload_to='ar/geo_star_point/animation_android/', verbose_name='Animation android'),
        ),
        migrations.AddField(
            model_name='geoarstarpoint',
            name='file_animation_ios',
            field=models.FileField(blank=True, null=True, upload_to='ar/geo_star_point/animation_ios/', verbose_name='Animation ios'),
        ),
    ]
