# Generated by Django 3.2.25 on 2025-12-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0181_alter_geoarstarpoint_screen_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanpicture',
            name='screen_title',
            field=models.JSONField(blank=True, help_text='Multiple titles to display on the screen (stored as a list)', null=True, verbose_name='Screen Title'),
        ),
    ]
