# Generated by Django 3.2.25 on 2025-12-03 05:52

import json
from django.db import migrations, models


def fix_invalid_json_data(apps, schema_editor):
    """Convert invalid text data to valid JSON format."""
    ScanPicture = apps.get_model('challenges', 'ScanPicture')

    for obj in ScanPicture.objects.exclude(screen_title__isnull=True).exclude(screen_title=''):
        try:
            # Try to parse as JSON first
            json.loads(obj.screen_title)
        except (json.JSONDecodeError, TypeError):
            # If it's not valid JSON, convert it to a JSON array with the text as the first element
            if isinstance(obj.screen_title, str):
                # Convert string to JSON array
                obj.screen_title = json.dumps([obj.screen_title])
            else:
                # If it's not a string, convert to empty array or keep as is
                obj.screen_title = json.dumps([])
            obj.save(update_fields=['screen_title'])


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0181_alter_geoarstarpoint_screen_title'),
    ]

    operations = [
        migrations.RunPython(fix_invalid_json_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='scanpicture',
            name='screen_title',
            field=models.JSONField(blank=True, help_text='Multiple titles to display on the screen (stored as a list)', null=True, verbose_name='Screen Title'),
        ),
    ]
