# Generated by Django 3.2.25 on 2026-02-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0182_alter_scanpicture_screen_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aruserprofile',
            name='randomizer_challenge_completed',
            field=models.IntegerField(default=0, verbose_name='Randomizer Challenges Completed'),
        ),
    ]
