# Generated by Django 3.2.25 on 2026-02-06 13:07

from django.db import migrations
from django.db.models import F


def merge_randomizer_data_forward(apps, schema_editor):
    """
    Merge RandomizerUserProfile data into ARUserProfile.

    For each user:
    1. If they have both profiles: Add randomizer points to AR points
    2. If they only have randomizer profile: Create AR profile with those points
    3. If they only have AR profile: Nothing to do
    """
    ARUserProfile = apps.get_model('challenges', 'ARUserProfile')
    RandomizerUserProfile = apps.get_model('randomizer_challenge', 'RandomizerUserProfile')

    merged_count = 0
    created_count = 0
    skipped_count = 0

    print("\n" + "="*60)
    print("Starting RandomizerUserProfile → ARUserProfile data migration")
    print("="*60)

    # Get all randomizer profiles
    randomizer_profiles = RandomizerUserProfile.objects.select_related('user').all()
    total_profiles = randomizer_profiles.count()

    print(f"\nFound {total_profiles} RandomizerUserProfile records to process")

    if total_profiles == 0:
        print("✓ No RandomizerUserProfile records found. Migration complete.")
        return

    for idx, randomizer_profile in enumerate(randomizer_profiles, 1):
        user = randomizer_profile.user

        try:
            # Try to get existing AR profile
            ar_profile = ARUserProfile.objects.get(user=user)

            # Both profiles exist - merge points
            old_ar_points = ar_profile.points
            ar_profile.points = ar_profile.points + randomizer_profile.points
            ar_profile.randomizer_challenge_completed = randomizer_profile.challenges_completed
            ar_profile.save()

            merged_count += 1
            print(f"  [{idx}/{total_profiles}] User {user.id}: Merged AR({old_ar_points}) + Randomizer({randomizer_profile.points}) = {ar_profile.points} points")

        except ARUserProfile.DoesNotExist:
            # No AR profile exists - create one with randomizer data
            ar_profile = ARUserProfile.objects.create(
                user=user,
                points=randomizer_profile.points,
                check_ins=0,
                challenge_completed=0,
                randomizer_challenge_completed=randomizer_profile.challenges_completed,
            )
            created_count += 1
            print(f"  [{idx}/{total_profiles}] User {user.id}: Created AR profile with {randomizer_profile.points} randomizer points")

    print("\n" + "="*60)
    print("Migration Summary:")
    print(f"  ✓ Created {created_count} new AR profiles")
    print(f"  ✓ Merged {merged_count} existing profiles")
    print(f"  ✓ Total processed: {total_profiles}")
    print("="*60 + "\n")


def merge_randomizer_data_reverse(apps, schema_editor):
    """
    Reverse migration: Not safe to reverse since we'd lose which points came from where.
    Log warning and do nothing.
    """
    print("\n" + "!"*60)
    print("WARNING: Cannot safely reverse this migration!")
    print("Data has been merged and cannot be split back without data loss.")
    print("If you need to reverse, restore from database backup.")
    print("!"*60 + "\n")


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0183_add_randomizer_challenge_completed'),
        ('randomizer_challenge', '0009_randomizersubmission_randomizeruserprofile'),
    ]

    operations = [
        migrations.RunPython(
            merge_randomizer_data_forward,
            merge_randomizer_data_reverse
        ),
    ]
