# Generated by Django 3.2.25 on 2026-02-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0184_merge_randomizer_profiles_data'),
    ]

    operations = [
    ]
