# Generated by Django 3.2.25 on 2026-02-10 09:43

from django.db import migrations, models


def remove_old_indexes_if_exist(apps, schema_editor):
    """Safely remove old indexes only if they exist"""
    db_alias = schema_editor.connection.alias

    # Define indexes to remove: (table_name, index_name)
    indexes_to_remove = [
        ('band_tracking_bandlocation', 'band_tracki_band_id_9c3f5a_idx'),
        ('band_tracking_bandlocation', 'band_tracki_timesta_6e8b2d_idx'),
        ('band_tracking_broadcastmessage', 'band_tracki_created_3e7aae_idx'),
        ('band_tracking_broadcastmessage', 'band_tracki_sent_at_95c3c1_idx'),
        ('band_tracking_broadcastmessage', 'band_tracki_is_dele_f8b2e3_idx'),
        ('band_tracking_notificationhistory', 'band_tracki_message_7a9c8d_idx'),
        ('band_tracking_notificationhistory', 'band_tracki_user_id_2b4f6e_idx'),
        ('band_tracking_notificationhistory', 'band_tracki_deliver_e5d7a2_idx'),
    ]

    with schema_editor.connection.cursor() as cursor:
        for table_name, index_name in indexes_to_remove:
            # Check if index exists
            cursor.execute("""
                SELECT 1
                FROM pg_indexes
                WHERE indexname = %s
            """, [index_name])

            if cursor.fetchone():
                # Index exists, drop it
                cursor.execute(f"DROP INDEX IF EXISTS {index_name}")


def reverse_remove_indexes(apps, schema_editor):
    """Reverse migration - recreate old indexes if needed"""
    pass  # We don't need to recreate old indexes on reverse


def add_new_indexes_if_not_exist(apps, schema_editor):
    """Safely add new indexes only if they don't exist"""

    # Define indexes to add: (table_name, index_name, create_sql)
    indexes_to_add = [
        ('band_tracking_bandlocation', 'band_tracki_band_id_fddf76_idx',
         'CREATE INDEX band_tracki_band_id_fddf76_idx ON band_tracking_bandlocation (band_id, timestamp DESC)'),
        ('band_tracking_bandlocation', 'band_tracki_timesta_4790de_idx',
         'CREATE INDEX band_tracki_timesta_4790de_idx ON band_tracking_bandlocation (timestamp DESC)'),
        ('band_tracking_broadcastmessage', 'band_tracki_created_162c24_idx',
         'CREATE INDEX band_tracki_created_162c24_idx ON band_tracking_broadcastmessage (created_at DESC)'),
        ('band_tracking_broadcastmessage', 'band_tracki_sent_at_6971c3_idx',
         'CREATE INDEX band_tracki_sent_at_6971c3_idx ON band_tracking_broadcastmessage (sent_at)'),
        ('band_tracking_broadcastmessage', 'band_tracki_is_dele_3a36c1_idx',
         'CREATE INDEX band_tracki_is_dele_3a36c1_idx ON band_tracking_broadcastmessage (is_deleted, created_at DESC)'),
        ('band_tracking_notificationhistory', 'band_tracki_message_1d926d_idx',
         'CREATE INDEX band_tracki_message_1d926d_idx ON band_tracking_notificationhistory (message_id, user_id)'),
        ('band_tracking_notificationhistory', 'band_tracki_user_id_599386_idx',
         'CREATE INDEX band_tracki_user_id_599386_idx ON band_tracking_notificationhistory (user_id, created_at DESC)'),
        ('band_tracking_notificationhistory', 'band_tracki_deliver_80e02a_idx',
         'CREATE INDEX band_tracki_deliver_80e02a_idx ON band_tracking_notificationhistory (delivered, read)'),
    ]

    with schema_editor.connection.cursor() as cursor:
        for table_name, index_name, create_sql in indexes_to_add:
            # Check if index exists
            cursor.execute("""
                SELECT 1
                FROM pg_indexes
                WHERE indexname = %s
            """, [index_name])

            if not cursor.fetchone():
                # Index doesn't exist, create it
                cursor.execute(create_sql)


def reverse_add_indexes(apps, schema_editor):
    """Reverse migration - drop new indexes if needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('band_tracking', '0001_initial'),
    ]

    operations = [
        # Safely remove old indexes using custom function
        migrations.RunPython(
            remove_old_indexes_if_exist,
            reverse_remove_indexes,
        ),
        migrations.AlterField(
            model_name='bandlocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        # Safely add new indexes using custom function
        migrations.RunPython(
            add_new_indexes_if_not_exist,
            reverse_add_indexes,
        ),
    ]
