# Generated by Django 3.2.25 on 2026-02-10 09:43

from django.db import migrations, models


def remove_old_indexes_if_exist(apps, schema_editor):
    """Safely remove old indexes only if they exist"""
    db_alias = schema_editor.connection.alias

    # Define indexes to remove: (table_name, index_name)
    indexes_to_remove = [
        ('band_tracking_bandlocation', 'band_tracki_band_id_9c3f5a_idx'),
        ('band_tracking_bandlocation', 'band_tracki_timesta_6e8b2d_idx'),
        ('band_tracking_broadcastmessage', 'band_tracki_created_3e7aae_idx'),
        ('band_tracking_broadcastmessage', 'band_tracki_sent_at_95c3c1_idx'),
        ('band_tracking_broadcastmessage', 'band_tracki_is_dele_f8b2e3_idx'),
        ('band_tracking_notificationhistory', 'band_tracki_message_7a9c8d_idx'),
        ('band_tracking_notificationhistory', 'band_tracki_user_id_2b4f6e_idx'),
        ('band_tracking_notificationhistory', 'band_tracki_deliver_e5d7a2_idx'),
    ]

    with schema_editor.connection.cursor() as cursor:
        for table_name, index_name in indexes_to_remove:
            # Check if index exists
            cursor.execute("""
                SELECT 1
                FROM pg_indexes
                WHERE indexname = %s
            """, [index_name])

            if cursor.fetchone():
                # Index exists, drop it
                cursor.execute(f"DROP INDEX IF EXISTS {index_name}")


def reverse_remove_indexes(apps, schema_editor):
    """Reverse migration - recreate old indexes if needed"""
    pass  # We don't need to recreate old indexes on reverse


class Migration(migrations.Migration):

    dependencies = [
        ('band_tracking', '0001_initial'),
    ]

    operations = [
        # Safely remove old indexes using custom function
        migrations.RunPython(
            remove_old_indexes_if_exist,
            reverse_remove_indexes,
        ),
        migrations.AlterField(
            model_name='bandlocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='bandlocation',
            index=models.Index(fields=['band', '-timestamp'], name='band_tracki_band_id_fddf76_idx'),
        ),
        migrations.AddIndex(
            model_name='bandlocation',
            index=models.Index(fields=['-timestamp'], name='band_tracki_timesta_4790de_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['-created_at'], name='band_tracki_created_162c24_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['sent_at'], name='band_tracki_sent_at_6971c3_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['is_deleted', '-created_at'], name='band_tracki_is_dele_3a36c1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['message', 'user'], name='band_tracki_message_1d926d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['user', '-created_at'], name='band_tracki_user_id_599386_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['delivered', 'read'], name='band_tracki_deliver_80e02a_idx'),
        ),
    ]
