# Generated by Django 2.2.28 on 2024-01-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240117_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_setup',
            field=models.BooleanField(default=False),
        ),
    ]
