# Generated by Django 2.2.28 on 2024-05-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
