# Generated by Django 2.2.28 on 2025-02-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'REGULAR'), (2, 'BAND')], default=1),
        ),
    ]
