# Generated by Django 2.2.28 on 2025-02-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_receive_points',
            field=models.BooleanField(default=False),
        ),
    ]
