# Generated by Django 3.2.25 on 2025-10-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
