# Generated by Django 3.2.25 on 2026-01-21 09:56

import django.core.validators
from django.db import migrations, models
import randomizer_challenge.models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer_challenge', '0005_create_default_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomizerchallenge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='randomizertrack',
            name='audio',
            field=models.FileField(upload_to='randomizer/audio/', validators=[randomizer_challenge.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'aac', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='randomizertrack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='randomizertrack',
            name='image',
            field=models.ImageField(upload_to='randomizer/images/', validators=[randomizer_challenge.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='randomizertrack',
            name='ranking',
            field=models.JSONField(blank=True, default=dict, help_text="Dynamic ranking object for this track (e.g., {'quality': 8, 'engagement': 6})", validators=[randomizer_challenge.models.validate_ranking]),
        ),
        migrations.AlterField(
            model_name='randomizertrack',
            name='track_number',
            field=models.PositiveIntegerField(help_text='Track number (must be unique within challenge)'),
        ),
    ]
