# Generated by Django 3.2.25 on 2026-01-29 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import randomizer_challenge.models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer_challenge', '0007_add_challenge_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/identifier for this video', max_length=255)),
                ('video', models.FileField(help_text='Video file to play after challenge completion', upload_to='challenge/videos/', validators=[randomizer_challenge.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm', 'mkv'])])),
                ('description', models.TextField(blank=True, help_text='Optional description of the video', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this video is active and available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, help_text='Optional: Link to a specific challenge. Leave blank for default video.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_videos', to='randomizer_challenge.randomizerchallenge')),
            ],
            options={
                'verbose_name': 'Challenge Video',
                'verbose_name_plural': 'Challenge Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
