# Generated by Django 3.2.25 on 2026-01-30 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import randomizer_challenge.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0182_alter_scanpicture_screen_title'),
        ('randomizer_challenge', '0008_challengevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomizerUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.BigIntegerField(default=0, verbose_name='Randomizer Challenge Points')),
                ('challenges_completed', models.IntegerField(default=0, verbose_name='Challenges Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='randomizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Randomizer User Profile',
                'verbose_name_plural': 'Randomizer User Profiles',
            },
        ),
        migrations.CreateModel(
            name='RandomizerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('COMPLETION', 'Challenge Completion'), ('SOCIAL_POINTS', 'Social Sharing Points')], default='COMPLETION', max_length=50)),
                ('result_file', models.FileField(blank=True, help_text="User's created audio/video mix or screenshot", null=True, upload_to='randomizer/submissions/', validators=[randomizer_challenge.models.validate_file_size])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='randomizer/thumbnails/', validators=[randomizer_challenge.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('description', models.TextField(blank=True, help_text="User's description or notes", null=True)),
                ('completion_data', models.JSONField(blank=True, help_text='Store track selections, scores, mix details, etc.', null=True)),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('declined_reason', models.TextField(blank=True, help_text='Reason for rejection', null=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Control whether this submission is public or private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='randomizer_challenge.randomizerchallenge')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='randomizer_submissions', to='challenges.sponsor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randomizer_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Randomizer Submission',
                'verbose_name_plural': 'Randomizer Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
