# Generated by Django 3.2.25 on 2026-02-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer_challenge', '0009_randomizersubmission_randomizeruserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomizersubmission',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UNAPPROVED', max_length=50),
        ),
    ]
