# Generated by Django 2.2.28 on 2024-05-01 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0028_auto_20240430_1107'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[(1, 'Spam'), (2, 'Pornography'), (3, 'Hatred and Bullying'), (4, 'Self-harm'), (5, 'Violent, Gory, and Harmful Content'), (6, 'Child Pornography'), (7, 'Illegal Activities'), (8, 'Deceptive Content'), (9, 'Copyright and Trademark Infringement'), (10, 'Other')], default=10, max_length=50, null=True)),
                ('custom_reason', models.TextField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenges')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reported Content/User',
                'verbose_name_plural': 'Reported Content/Users',
            },
        ),
    ]
