# Generated by Django 2.2.28 on 2024-05-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_reportedcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcontent',
            name='reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Spam'), (2, 'Pornography'), (3, 'Hatred and Bullying'), (4, 'Self-harm'), (5, 'Violent, Gory, and Harmful Content'), (6, 'Child Pornography'), (7, 'Illegal Activities'), (8, 'Deceptive Content'), (9, 'Copyright and Trademark Infringement'), (10, 'Other')], default=10, max_length=50, null=True),
        ),
    ]
