# Generated by Django 2.2.28 on 2024-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20240501_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
