# Generated by Django 2.2.28 on 2024-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_contactus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcontent',
            name='reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Spam'), (2, 'Pornography'), (3, 'Hate'), (4, 'Bullying'), (5, 'Self-Harm'), (6, 'Violent'), (7, 'Gory'), (8, 'Harmful Content'), (9, 'Child Porn'), (10, 'Illegal Activities'), (11, 'Deceptive'), (12, 'Copyright & Trademark Infringement'), (13, 'Other')], default=13, max_length=50, null=True),
        ),
    ]
