# Generated by Django 2.2.28 on 2024-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20240621_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedcontent',
            name='block_reported_user',
            field=models.BooleanField(default=False),
        ),
    ]
